name: CI with Trivy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Docker Buildx for building the image
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build the Docker image
      - name: Build Docker image
        run: docker build -t trivy-demo-app:1.1 .

      # Install Trivy
      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin

      # Scan the image with Trivy
      - name: Scan image with Trivy
        run: |
          trivy image --exit-code 1 --severity CRITICAL,HIGH trivy-demo-app:1.1

      # Tag and push the image to Docker Hub
      - name: Push to Docker Hub
        run: |
          docker tag trivy-demo-app:1.1 ${{ secrets.DOCKERHUB_USERNAME }}/trivy-demo-app:1.1
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/trivy-demo-app:1.1
