name: CI with Trivy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Docker Buildx for building the image
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build the Docker image with a dynamic tag
      - name: Build Docker image
        run: |
          docker build -t trivy-demo-app:1.${{ github.run_number }} .

      # Install Trivy
      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin

      # Scan the image with Trivy
      - name: Scan image with Trivy
        run: |
          trivy image --exit-code 1 --severity CRITICAL,HIGH trivy-demo-app:1.${{ github.run_number }}

      # Tag and push the image to Docker Hub with version and latest tags
      - name: Push to Docker Hub
        run: |
          # Push the versioned tag (e.g., 1.3)
          docker tag trivy-demo-app:1.${{ github.run_number }} ${{ secrets.DOCKERHUB_USERNAME }}/trivy-demo-app:1.${{ github.run_number }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/trivy-demo-app:1.${{ github.run_number }}
          # Push the 'latest' tag
          docker tag trivy-demo-app:1.${{ github.run_number }} ${{ secrets.DOCKERHUB_USERNAME }}/trivy-demo-app:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/trivy-demo-app:latest
